language: ruby

rvm: $RUBY_VERSION

env:
  - PUPPET_VERSION="~> 4.3.0" RUBY_VERSION="2.6.0" TARGET=test
  - PUPPET_VERSION="~> 5.5.16" RUBY_VERSION="2.6.0" TARGET=test
  - PUPPET_VERSION="~> 6.13.0" RUBY_VERSION="2.7.0" TARGET=test
  - TARGET=acceptance RUBY_VERSION="2.5.1" BEAKER_setfile=spec/acceptance/nodesets/ubuntu-1604-x64.yml

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system
  - gem --version

script: "rake $TARGET"

sudo: false

services: docker

jobs:
  allow_failures:
    - env: TARGET=acceptance RUBY_VERSION="2.5.1" BEAKER_setfile=spec/acceptance/nodesets/ubuntu-1604-x64.yml
