language: ruby

rvm: $RUBY_VERSION

env:
  - PUPPET_VERSION="~> 3.6.0" RUBY_VERSION="2.1.0"
  - PUPPET_VERSION="~> 3.7.0" RUBY_VERSION="2.1.0"
  - PUPPET_VERSION="~> 4.3.0" RUBY_VERSION="2.4.0"
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes RUBY_VERSION="2.4.0"
  - PUPPET_VERSION="~> 5.5.0" RUBY_VERSION="2.4.0"

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version

script: "rake test"

sudo: false
